ITEM.name = "Soil"
ITEM.uniqueID = "soil"
ITEM.model = "models/props_junk/plasticbucket001a.mdl"
ITEM.description = "A bag of soil."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 10
ITEM.category = "Farming"
ITEM.color = Color(50, 255, 50)