ITEM.name = "AK-47"
ITEM.description = "A pre-war variant of the Kalash firing rifle rounds."
ITEM.model = "models/weapons/w_rif_ak47.mdl"
ITEM.class = "weapon_ak47"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.chance = 8
ITEM.rare = true