ITEM.name = "Abzats"
ITEM.description = "A very heavy shotgun, meant firing shotgun shells in a box magazine."
ITEM.model = "models/redux/weapons/abzats.mdl"
ITEM.class = "tfa_metro_abzatz"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.height = 3
ITEM.chance = 1
ITEM.rare = true