ITEM.name = "Bastard"
ITEM.description = "A crude SMG made out of a mix of rubber and crude steel. Firing Crude SMG Rounds."
ITEM.model = "models/devcon/mrp/weapons/w_bastard.mdl"
ITEM.class = "tfa_metro_exo_bastard"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 1
ITEM.chance = 45
ITEM.rare = true