ITEM.name = "C96"
ITEM.description = "A pre-war pistol utilizing pistol munitions."
ITEM.model = "models/weapons/w_pist_c228.mdl"
ITEM.class = "weapon_c96_1"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 1
ITEM.chance = 3
ITEM.rare = true
