ITEM.name = "Acoustic Guitar"
ITEM.description = "A makeshift six string acoustic guitar."
ITEM.model = "models/kek1ch/dev_guitar.mdl"
ITEM.class = "guitar_stalker"
ITEM.weaponCategory = "melee"
ITEM.flag = "v"
ITEM.width = 2
ITEM.height = 1
ITEM.chance = 28