ITEM.name = "Kalash Special"
ITEM.description = "A crude version of the pre-war AKS-74U, it fires 5.56x51mm Crude."
ITEM.model = "models/redux/weapons/aksu.mdl"
ITEM.class = "tfa_metro_exo_ak47u"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 1
ITEM.chance = 17
ITEM.rare = yes