ITEM.name = "Kalash 2012"
ITEM.description = "A  pre-war version of the Kalash firing 5.45x45mm MGR."
ITEM.model = "models/redux/weapons/kal2012.mdl"
ITEM.class = "tfa_metro_exo_2012"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 1
ITEM.chance = 4
ITEM.rare = true