ITEM.name = "Kalash"
ITEM.description = "A makeshift version of the popular AK-74, it fires 7.62x51mm Crude"
ITEM.model = "models/redux/weapons/ak74.mdl"
ITEM.class = "tfa_metro_exo_ak74"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.chance = 12
ITEM.rare = true