ITEM.name = "PMM"
ITEM.description = "Lightweight Russian pistol chambered in 9x18mm."
ITEM.model = "models/weapons/w_stalker_makarov.mdl"
ITEM.class = "stalker_makarov"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.chance = 20
ITEM.rare = true