ITEM.name = "RPK"
ITEM.description = "A pre-war variant of the Kalash firing 7.62x51mm MGR."
ITEM.model = "models/redux/weapons/rpk.mdl"
ITEM.class = "tfa_metro_exo_rpk"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.chance = 4
ITEM.rare = true