ITEM.name = "SVUMK-2"
ITEM.description = "A foreign bullpup variant of the SVDM-2. Something about its design causes it to shoot slower than most semi-automatic snipers. Although shorter in size, its suppressor gives it roughly the same length as its Russian counterpart. The rifle is chambered in 7.62x54mmR"
ITEM.model = "models/weapons/w_stalker_svu.mdl"
ITEM.class = "stalker_svu"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.chance = 1
ITEM.rare = true