ITEM.name = "Saiga-12"
ITEM.description = "A pre-war automatic shotgun firing 12 gauge shotgun shells through a modified Kalash magazines."
ITEM.model = "models/redux/weapons/saiga.mdl"
ITEM.class = "tfa_metro_saiga"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.chance = 8
ITEM.rare = true