ITEM.name = "Tunder S14"
ITEM.description = "A bullpup assault rifle of unknown origins. Aside from its complicated components and bizarre look and worn exterior, it still seems like a viable weapon. It is chambered 7.62x54mmR"
ITEM.model = "models/weapons/w_stalker_oc14.mdl"
ITEM.class = "stalker_ots"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 1
ITEM.chance = 7
ITEM.rare = true