ITEM.name = "Tihar"
ITEM.description = "A pneumatic rifle firing 6 steel bolts with sharpened ends. The rifle typically requires pumping after 6 shots."
ITEM.model = "models/redux/weapons/tihar.mdl"
ITEM.class = "tfa_metro_exo_tihar_test"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 1
ITEM.chance = 7
ITEM.rare = true