ITEM.name = "Uboinik"
ITEM.description = "An automatic shotgun with a revolver style loading system. Firing 6 Gauge shells."
ITEM.model = "models/redux/weapons/uboinik.mdl"
ITEM.class = "tfa_metro_autoshotgun"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 1
ITEM.chance = 7
ITEM.rare = true