ITEM.name = "VSV"
ITEM.description = "A crude version of the pre-war sniper rifle, it comes with an automatic/semi auto switch, and fires 7.62x45mm crude."
ITEM.model = "models/redux/weapons/vsv.mdl"
ITEM.class = "tfa_metro_exo_vsv"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 1
ITEM.chance = 12
ITEM.rare = true