ITEM.name = "VSSK"
ITEM.description = "A Pre-War sniper rifle, it appears rusted and fires 6.5mm Rounds."
ITEM.model = "models/redux/weapons/clapper.mdl"
ITEM.class = "rwp_tfa_sniper_vssk"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 1
ITEM.chance = 2
ITEM.rare = true